---
title: Rationale
timezone: UTC
collections:
  our-work:
    title: Our work
    output: true
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
  shop:
    title: Shop
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: our-work
  values:
    layout: project
    excerpt_text: 
    year: 
    images:
    - image: 
      alt: 
    thumb_image:
      image: 
      alt: 
    og_image: 
- scope:
    path: ''
    type: resources
  values:
    layout: resource
    author: 
    imgcount: 
    images:
    - image: 
      alt: 
    thumb_image:
      image: 
      alt: 
    download_file: 
    og_image: 
- scope:
    path: ''
    type: store
  values:
    layout: product-detail
    price: 
    buylink: 
    imgcount: 
    images:
    - image: 
      alt: 
    thumb_image:
      image: 
      alt: 
    og_image: 
- scope:
    path: ''
    type: posts
  values:
    layout: post-detail
    excerpt_text: 
    featured_image:
      image: 
      alt: 
    detail_images:
    - image: 
      alt: 
    og_image: 
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- README.md
- node_modules/
- package.json
- gulpfile.js
description: Rationale provides world-class expertise in design, identity systems,
  and envisioning across multiple mediums.
og_image: "/uploads/rationale_og.jpg"
