---
title: Rationale v2
timezone: UTC
collections:
  our-work:
    title: Our work
    output: true
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
  store:
    title: Store
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: our-work
    type: our work
  values:
    layout: project
permalink: pretty
plugins_dir: [jekyll-autoprefixer, jekyll-bower]
sass:
  style: compressed
bower:
  reset-css: reset-css
  sassy-maps: sassy-maps
  singularity: singularity
  breakpoint-sass: breakpoint-sass
exclude:
  ["src/_bower_components", "bower.json"]
