---
title: Rationale v2
timezone: UTC
collections:
  our-work:
    title: Our work
    output: true
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
  store:
    title: Store
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: our-work
  values:
    layout: project
    year:
    imgcount:
    images:
    -
    thumb_image:
    og_image:
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- README.md
- node_modules/
- package.json
- gulpfile.js
description: Rationale provides world-class expertise in design, identity systems,
  and envisioning across multiple mediums.
